---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-1
  name: frontend-1
  namespace: dev-thib-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-1
    spec:
      containers:
        - image: registry.ocp.lan:15443/lab/ubidebug:latest
        name: image1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-1
  name: service-frontend-1
  namespace: dev-thib-1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-1
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: frontend-1
  name: frontend-1
  namespace: dev-thib-1
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: frontend-1
    weight: 100
