apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap-1
  namespace: dev-thib-1
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! from dev-thib-1 </h1>
    </html>
