apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: tektutor2-ingress
  namespace: openshift-ingress-operator
spec:
  domain: tektutor2.ocp.lan
  endpointPublishingStrategy:
    type: LoadBalancerService
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  logging:
    access:
      destination:
        type: Container
  replicas: 2
  namespaceSelector:
    matchLabels:
      type: sharded
