apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stasto-rolebindings
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: stasto
