apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    type: sharded 
  name: nginx-sharded
  namespace: tektutor2
spec:
  host: toto.tektutor2.ocp.lan
  to:
    kind: Service
    name: nginx