apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: {{ .Values.namespace.name }}-ingress
  namespace: openshift-ingress-operator
spec:
  domain: {{ .Values.namespace.name }}.ocp.lan
  endpointPublishingStrategy:
    type: LoadBalancerService
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  logging:
    access:
      destination:
        type: Container
  replicas: 2
  namespaceSelector:
    matchLabels:
      type: sharded