apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: {{ .Values.namespace.name }}
spec:
  hard:
    pods: {{ .Values.resourcequota.pods }}
    requests.cpu: {{ .Values.resourcequota.requests.cpu }}
    requests.memory: {{ .Values.resourcequota.requests.memory }}
    limits.cpu: {{ .Values.resourcequota.limits.cpu }}
    limits.memory: {{ .Values.resourcequota.limits.memory }}