apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.namespace.name }}-sharded
  namespace: {{ .Values.namespace.name }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: 9898
  to:
    kind: Service
    name: nginx