apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.namespace.name }}-sharded
  namespace: {{ .Values.namespace.name }}
spec:
  host: toto.{{ .Values.namespace.name }}.ocp.lan
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nginx