apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap-1
  namespace: dev-thib-1
data:
  index.html: |
    <!DOCTYPE html>
      <html>
       <body>
         <p><?php echo "hostname is:".gethostname(); ?></p>
       </body>
    </html>
