apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-1
  name: service-eip-frontend-1
  namespace: dev-thib-1
spec:
  externalTrafficPolicy: Cluster
  externalIPs:
  - 192.168.22.1
  ports:
  - nodePort: 32000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-1
  type: LoadBalancer
