apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-1
  name: service-eip-frontend-1
  namespace: dev-thib-1
spec:
  externalIPs:
  - 192.168.50.10
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-1
